<a href="https://colab.research.google.com/github/reban87/machine_learning_workshop/blob/main/01-introduction/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra Basics


    Vector operations
    Multiplication
        Vector-vector multiplication
        Matrix-vector multiplication
        Matrix-matrix multiplication
    Identity matrix
    Inverse


In [1]:
import numpy as np

Vector operations

In [2]:
u = np.array([2, 4, 5, 6])

In [3]:
2 * u

array([ 4,  8, 10, 12])

In [8]:
v = np.array([1, 0, 0, 2])

In [9]:
u + v

array([3, 4, 5, 8])

In [10]:
u * v

array([ 2,  0,  0, 12])

Multiplication

In [22]:
v.shape # In 1-d array, the shape function gives the number of elements in an
         # array

(4,)

In [21]:
v.shape[0]

4

In [23]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    print(n)

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [24]:
vector_vector_multiplication(u, v)

4


14.0

In [20]:
u.dot(v)

14

In [25]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])


In [26]:
U.shape

(3, 4)

In [27]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result


In [29]:
matrix_vector_multiplication(U, v)

4
4
4


array([14.,  5.,  5.])

In [30]:
U.dot(v)

array([14,  5,  5])

Identity matrix

In [31]:
I = np.eye(3)

In [32]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])


In [37]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [38]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])