<a href="https://colab.research.google.com/github/reban87/machine_learning_workshop/blob/main/01-introduction/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to NumPy

### What we will cover? ⚡
- Creating arrays
- Multi dimensional arrays
- Randomly generated arrays
- Element wise operations
  - Comparision operations
  - Logical operations
- Summarizing operations


In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

Creating arrays

Arrays are the building blocks of Numpy, and they can be thought of as lists but with enhanced features.
Creating Arrays with Zeros, Ones, or Constants
You can create arrays filled with zeros, ones, or any constant using np.zeros(), np.ones(), and np.full():

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [7]:
a = np.array([1, 2, 3, 5, 7, 12])
a


array([ 1,  2,  3,  5,  7, 12])

In [8]:
a[2] = 10

In [9]:
a

array([ 1,  2, 10,  5,  7, 12])

In [12]:
np.arange(3, 10)


array([3, 4, 5, 6, 7, 8, 9])

In [19]:
np.linspace(0, 100, 11) # creates arrays with evenly spaced numbers within a specified range:

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Multidimensional arrays

In [20]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


In [22]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
n[0, 1] = 20

In [24]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [25]:
n[2] = [1, 1, 1]

In [26]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [27]:
n[:, 2] = [0, 1, 2]


In [28]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

Randomly generated arrays

Numpy can create arrays filled with random numbers. To ensure reproducibility, you can set a seed using np.random.seed():

Every time you run this code with np.random.seed(42), it will generate the exact same three random numbers. If you remove or change the seed value, the sequence of random numbers will change.

In [44]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [45]:
np.random.seed(2)
np.random.randn(5, 2)


array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [47]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

Element-wise
You can perform operations on entire arrays element by element:

In [50]:
a = np.arange(5)
a


array([0, 1, 2, 3, 4])

In [53]:
b = (10 + (a * 2))

In [54]:
b

array([10, 12, 14, 16, 18])

Comparison operations

You can perform element-wise comparisons and create boolean arrays:

In [56]:
a

array([0, 1, 2, 3, 4])

In [57]:
a >= 2


array([False, False,  True,  True,  True])

In [58]:
b

array([10, 12, 14, 16, 18])

In [59]:
a > b


array([False, False, False, False, False])

Summarizing

Numpy provides functions for summarizing array data:

In [61]:
a

array([0, 1, 2, 3, 4])

In [62]:
a.std()

1.4142135623730951

In [64]:
a.min()

0

In [65]:
a.max()

4

In [66]:
a.sum()

10